# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Nalxf
subtitle: 个人博客在看了网上各种风格的教程,终于是建立起来了. 希望自己能 力学笃行 不断前进                        #网站副标题
description: 希望自己能 力学笃行 不断前进                      #网站描述 SEO
author: 李学峰
language: zh-Hans                        #网站使用的语言
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
## 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，则请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: http://Nalxf.com                         #网址
root: /                                       #网站根目录
permalink: :year/:month/:day/:title/          #文章的 永久链接 格式
permalink_defaults:                           #永久链接中各部分的默认值

# Directory
source_dir: source                            #资源文件夹，这个文件夹用来存放内容。
public_dir: public                            #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags                                 #标签文件夹
archive_dir: archives                         #归档文件夹
category_dir: categories                      #分类文件夹
code_dir: downloads/code                      #Include code 文件夹
i18n_dir: :lang                               #国际化（i18n）文件夹
skip_render: README.md                                  #跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

# Writing
## 如果您刚刚开始接触Hexo，通常没有必要修改这一部分的值。
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting  (首页设置)
# path: Root path for your blogs index page. (default = '')  路径
# per_page: Posts displayed per page. (0 = disable pagination) 分页相关配置
# order_by: Posts order. (Order by date descending by default) 文章的顺序。(默认按日期降序顺序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag 分类 & 标签
default_category: uncategorized
category_map:                       #分类别名
tag_map:                            #标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:Nalxf/Nalxf.github.io.git,master
    coding: https://git.coding.net/SowSorrow/SowSorrow.coding.me.git,master
    # https://git.coding.net/SowSorrow/Nalxf.git
    # repository: git@github.com:Nalxf/Nalxf.github.io.git
    # branch: master


# Extensions
## Plugins: http://hexo.io/plugins/
plugins: hexo-generate-feed


live2d:
  model: shizuku
  bottom: -30


# css3常用动画+动画库
## http://www.cnblogs.com/starof/p/4968769.html
